# Generated by Django 5.0.7 on 2024-08-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('individual_form', 'Individual Form'), ('team_form', 'Team Form'), ('sparring', 'Sparring'), ('team_sparring', 'Team Sparring'), ('special_technique', 'Special Technique'), ('team_special_technique', 'Team Special Technique')], max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='Work',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='user',
        ),
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteCategoryAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_associations', to='main.athlete')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_associations', to='main.category')),
            ],
            options={
                'unique_together': {('athlete', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='main.athlete')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.team')),
            ],
            options={
                'unique_together': {('athlete', 'team')},
            },
        ),
    ]
