# Generated by Django 5.0.7 on 2024-08-13 11:11

import datetime
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_athlete_coach_media_gender_staff_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='departure_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='coach',
            name='departure_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='passport_photo',
            field=models.ImageField(upload_to=main.models.upload_to),
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='passport_photo',
            field=models.ImageField(upload_to=main.models.upload_to),
        ),
        migrations.AlterField(
            model_name='media',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='passport_photo',
            field=models.ImageField(upload_to=main.models.upload_to),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='passport_photo',
            field=models.ImageField(upload_to=main.models.upload_to),
        ),
    ]
