# Generated by Django 5.0.7 on 2024-08-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_athlete_weight_alter_athlete_name_alter_coach_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='main.country'),
        ),
    ]
