# Generated by Django 5.0.7 on 2024-08-23 01:17

import datetime
import django.db.models.deletion
import django.utils.timezone
import main1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('individual_form', 'Individual Form'), ('team_form', 'Team Form'), ('sparring', 'Sparring'), ('team_sparring', 'Team Sparring'), ('special_technique', 'Special Technique'), ('team_special_technique', 'Team Special Technique')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_photo', models.ImageField(upload_to=main1.models.upload_to)),
                ('name', models.CharField(max_length=100)),
                ('id_passport_number', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('role', models.CharField(choices=[('Photographer', 'Photographer'), ('Journalist', 'Journalist'), ('Videographer', 'Videographer')], max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('media_house', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_photo', models.ImageField(upload_to=main1.models.upload_to)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('id_passport_number', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('Photographer', 'Photographer'), ('Journalist', 'Journalist'), ('Videographer', 'Videographer')], max_length=100)),
                ('contacts', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passport_photo', models.ImageField(upload_to=main1.models.upload_to)),
                ('id_passport_number', models.CharField(max_length=50, null=True, blank=True)),
                ('passport', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_date_of_issue', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacts', models.CharField(max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('is_athlete', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('Assistant', 'Assistant'), ('Head', 'Head'), ('Senior', 'Senior')], max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_accommodation', to='main1.accommodation')),
                ('belt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_belt', to='main1.belt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_category', to='main1.category')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region', to='main1.club')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profiles', to='main1.country')),
                ('passport_place_of_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_passports', to='main1.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passport_photo', models.ImageField(upload_to=main1.models.upload_to)),
                ('id_passport_number', models.CharField(max_length=50, null=True, blank=True)),
                ('passport', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_date_of_issue', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacts', models.CharField(max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_accommodation', to='main1.accommodation')),
                ('belt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_belt', to='main1.belt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_associations', to='main1.category')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region', to='main1.club')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_coach', to='main1.coach')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profiles', to='main1.country')),
                ('passport_place_of_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_passports', to='main1.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main1.category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main1.country')),
                ('members', models.ManyToManyField(blank=True, related_name='team_members', to='main1.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='main1.athlete')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='main1.team')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='athletes', to='main1.team'),
        ),
    ]
