# Generated by Django 5.0.7 on 2024-08-23 04:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3, null=True),
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='category',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='contacts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='departure_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='passport_place_of_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_passports', to='main1.country'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3, null=True),
        ),
        migrations.RemoveField(
            model_name='coach',
            name='category',
        ),
        migrations.AlterField(
            model_name='coach',
            name='contacts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='departure_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='level',
            field=models.CharField(blank=True, choices=[('Assistant', 'Assistant'), ('Head', 'Head'), ('Senior', 'Senior')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='passport_place_of_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_passports', to='main1.country'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='athlete_associations', to='main1.category'),
        ),
        migrations.AddField(
            model_name='coach',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='coach_category', to='main1.category'),
        ),
    ]
