# Generated by Django 5.0.7 on 2024-09-03 12:41

import django.db.models.deletion
import main1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0002_alter_athlete_blood_group_remove_athlete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('edition', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='passport_photo',
            field=models.ImageField(blank=True, upload_to=main1.models.upload_to),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='passport_photo',
            field=models.ImageField(blank=True, upload_to=main1.models.upload_to),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Photographer', 'Photographer'), ('Handy man', 'Handy man'), ('Security', 'security'), ('Driver', 'driver'), ('Technitian ', 'Technitian'), ('Water dist', 'Water dist')], max_length=100),
        ),
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(blank=True, max_length=255, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main1.athlete')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main1.category')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main1.coach')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main1.tournament')),
            ],
        ),
    ]
